# Values for Development environment (DigitalOcean)
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "develop-079ac8cdce90e49299db0dbd3125b7871a968f9b"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: develop.g3developer.online
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nexo-fe-develop-tls
      hosts:
        - develop.g3developer.online

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: development
  API_URL: http://nexo-be-develop:3000
  NEXT_PUBLIC_API_URL: https://develop.api.g3developer.online
  NEXT_PUBLIC_KEYCLOAK_URL: https://develop.auth.g3developer.online
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-web

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "079ac8c"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
