apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexo-auth.fullname" . }}
  labels:
    {{- include "nexo-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.managementPort | default 9000 }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "nexo-auth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
