# Values for Production environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "main-2c344367dfc86d7d70387e2f9f8cc4f64dbc2d22"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: fe.nexo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: production
  API_URL: http://nexo-be-prod:3000
  NEXT_PUBLIC_API_URL: http://be.nexo.local
  NEXT_PUBLIC_KEYCLOAK_URL: http://auth.nexo.local
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-web

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podAnnotations:
  app.kubernetes.io/commit: "2c34436"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
