# Values for Production environment (DigitalOcean)
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "latest"
  pullPolicy: Always


ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: nexo.local
      paths:
        - path: /
          pathType: Prefix
