# Values for Development environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "develop-6e8adbae224a8da33c03f0a3033556dea48f7489"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: develop-fe.nexo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: development
  API_URL: http://nexo-be-develop:3000
  NEXT_PUBLIC_API_URL: http://develop-be.nexo.local
  NEXT_PUBLIC_KEYCLOAK_URL: http://develop-auth.nexo.local
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-web

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "6e8adba"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
