# Values for QA environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/nexo-fe
  tag: "qa-b0a3e980a7e3b60d9012d6e017c0e1d3161d8b04"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: qa-fe.nexo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: production
  API_URL: http://nexo-be-qa:3000
  NEXT_PUBLIC_API_URL: http://qa-be.nexo.local
  NEXT_PUBLIC_KEYCLOAK_URL: http://qa-auth.nexo.local
  NEXT_PUBLIC_KEYCLOAK_REALM: nexo
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nexo-web

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "b0a3e98"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
